# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My Card' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My Card
  # pod 'DeviceKit', '~> 0.3.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'

end
